/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edcompanies;

import com.edcompanies.data.Account;
import com.edcompanies.data.Admin;
import java.awt.AlphaComposite;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Ed
 */
public class TMSystem extends javax.swing.JFrame {

    private static final Color HIGHLIGHT_COLOR=new Color(53,124,153);
    private static final Color ORIGINAL_COLOR=new Color(3,127,178);
    private static TMSystem mainFrame=new TMSystem();

    /**
     * Creates new form TMSystem
     */
    public TMSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigation = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dashboardLabel = new javax.swing.JLabel();
        timeslotLabel = new javax.swing.JLabel();
        roomsLabel = new javax.swing.JLabel();
        viewTimetableLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        navigation.setBackground(new java.awt.Color(3, 127, 178));
        navigation.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(3, 127, 178));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        dashboardLabel.setBackground(new java.awt.Color(3, 127, 178));
        dashboardLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dashboardLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardLabel.setText("DASHBOARD");
        dashboardLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        dashboardLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dashboardLabelMousePressed(evt);
            }
        });

        timeslotLabel.setBackground(new java.awt.Color(3, 127, 178));
        timeslotLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        timeslotLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeslotLabel.setText("CLASSES");
        timeslotLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        timeslotLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timeslotLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timeslotLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                timeslotLabelMousePressed(evt);
            }
        });

        roomsLabel.setBackground(new java.awt.Color(3, 127, 178));
        roomsLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        roomsLabel.setForeground(new java.awt.Color(255, 255, 255));
        roomsLabel.setText("ROOMS");
        roomsLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        roomsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomsLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomsLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roomsLabelMousePressed(evt);
            }
        });

        viewTimetableLabel.setBackground(new java.awt.Color(3, 127, 178));
        viewTimetableLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewTimetableLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewTimetableLabel.setText("VIEW TIMETABLE");
        viewTimetableLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        viewTimetableLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTimetableLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewTimetableLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewTimetableLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(timeslotLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roomsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(viewTimetableLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(dashboardLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeslotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewTimetableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        imageLabel.setText("jLabel2");

        nameLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nameLabel.setText("jLabel2");

        javax.swing.GroupLayout navigationLayout = new javax.swing.GroupLayout(navigation);
        navigation.setLayout(navigationLayout);
        navigationLayout.setHorizontalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationLayout.createSequentialGroup()
                .addGap(0, 49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(navigationLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(nameLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navigationLayout.setVerticalGroup(
            navigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        mainPanel.setLayout(new java.awt.CardLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edcompanies/resources/must-logo.png"))); // NOI18N

        jButton1.setText("Log out");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)
                        .addComponent(jButton1)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewTimetableLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTimetableLabelMouseExited
        // TODO add your handling code here:
        viewTimetableLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_viewTimetableLabelMouseExited

    private void viewTimetableLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTimetableLabelMouseEntered
        // TODO add your handling code here:
        viewTimetableLabel.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_viewTimetableLabelMouseEntered

    private void roomsLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsLabelMousePressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.invalidate();
        mainPanel.add(new Rooms());
        Rooms.populateBuildingsCombobox();
        mainPanel.revalidate();
        
        
    }//GEN-LAST:event_roomsLabelMousePressed

    private void roomsLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsLabelMouseExited
        // TODO add your handling code here:
        roomsLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_roomsLabelMouseExited

    private void roomsLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsLabelMouseEntered
        // TODO add your handling code here:
        roomsLabel.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_roomsLabelMouseEntered

    private void timeslotLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeslotLabelMousePressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.invalidate();
        mainPanel.add(new Classes());
        Classes.populateFacultyCombobox();
        mainPanel.revalidate();
    }//GEN-LAST:event_timeslotLabelMousePressed

    private void timeslotLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeslotLabelMouseExited
        // TODO add your handling code here:
        timeslotLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_timeslotLabelMouseExited

    private void timeslotLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeslotLabelMouseEntered
        // TODO add your handling code here:
        timeslotLabel.setForeground(Color.DARK_GRAY);
    }//GEN-LAST:event_timeslotLabelMouseEntered

    private void dashboardLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLabelMousePressed
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.invalidate();
        mainPanel.add(new Dashboard());
        mainPanel.revalidate();
    }//GEN-LAST:event_dashboardLabelMousePressed

    private void dashboardLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLabelMouseExited
        // TODO add your handling code here:
        dashboardLabel.setForeground(Color.WHITE);
    }//GEN-LAST:event_dashboardLabelMouseExited

    private void dashboardLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardLabelMouseEntered
        // TODO add your handling code here:
        dashboardLabel.setForeground(Color.DARK_GRAY);

    }//GEN-LAST:event_dashboardLabelMouseEntered

    private void viewTimetableLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTimetableLabelMouseClicked
        // TODO add your handling code here:
        mainPanel.removeAll();
        mainPanel.invalidate();
        mainPanel.add(new Timetable());
        mainPanel.revalidate();
        
    }//GEN-LAST:event_viewTimetableLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    
   
    
    public static void paintScreen(){
        getAdminInfo();
        createProfileImage();
        imageLabel.setText("");
        nameLabel.setText(admin.getFirstName()+" "+admin.getSecondName());
        mainPanel.add(new Dashboard());
        mainFrame.setVisible(true);
        
    }
    
    private static void getAdminInfo(){
        try{
            Socket socket;
            Thread.sleep(1000);
            
            socket = new Socket("localhost", 4242);
            System.out.println("Waiting for admin info...");
            
            ObjectInputStream objectInputStream=new ObjectInputStream(socket.getInputStream());
            admin = (Admin)objectInputStream.readObject();
            
            objectInputStream.close();
            socket.close();
            
            
        }
        catch(Exception ex){
            ex.printStackTrace();
        }
            
        
    }
    private static Admin admin;
    
    
    
    public static void applyQualityRenderingHints(Graphics2D g2d) {
        g2d.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_COLOR_RENDERING, RenderingHints.VALUE_COLOR_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_DITHERING, RenderingHints.VALUE_DITHER_ENABLE);
        g2d.setRenderingHint(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);

}
    
    private static void createProfileImage(){
        try {
            BufferedImage master=ImageIO.read(new FileInputStream(admin.getImagePath()));
            int diameter=Math.min(master.getWidth(),master.getHeight());
            BufferedImage mask=new BufferedImage(master.getWidth(),master.getHeight(),BufferedImage.TYPE_INT_ARGB);
            Graphics2D g2d=mask.createGraphics();
            applyQualityRenderingHints(g2d);
            g2d.fillOval(0,0,diameter-1,diameter-1);
            g2d.dispose();
            BufferedImage masked=new BufferedImage(diameter,diameter,BufferedImage.TYPE_INT_ARGB);
            g2d=masked.createGraphics();
            applyQualityRenderingHints(g2d);
            int x=(diameter-master.getWidth());
            int y=(diameter-master.getHeight());
            g2d.drawImage(master, x, y,null);
            g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.DST_IN));
            g2d.drawImage(mask, 0, 0,null);
            g2d.dispose();
            imageLabel.setIcon(new ImageIcon(masked.getScaledInstance(150, 150,Image.SCALE_SMOOTH )));
            
            
        } catch (IOException ex) {
            System.out.println(ex);
        }
        
        
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TMSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TMSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TMSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TMSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //mainFrame.dispose();
                //mainFrame.setUndecorated(true);
                
                paintScreen();
              
        }});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardLabel;
    private static javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JPanel mainPanel;
    private static javax.swing.JLabel nameLabel;
    private javax.swing.JPanel navigation;
    private javax.swing.JLabel roomsLabel;
    private javax.swing.JLabel timeslotLabel;
    private javax.swing.JLabel viewTimetableLabel;
    // End of variables declaration//GEN-END:variables
}
